version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  transcoding-service-1:
    build: ./TranscodingService
    environment: 
      - PYTHONUNBUFFERED=1
    depends_on: 
      - minio
      - kafka
  
  video-post-processor-1:
    build: ./VideoPostProcessor
    environment: 
      - PYTHONUNBUFFERED=1
    depends_on: 
      - minio
      - kafka

  consumer-proxy-service-1:
    build: ./ConsumerProxyService
    ports:
      - 8000:8000
    depends_on: 
      - metadata-storage-service-1
  
  metadata-storage-service-1:
    build: ./MetadataStorageService
    ports:
      - 4000:4000
    depends_on: 
      - elasticsearch1
  
  edge-node-provider-service-1:
    build: ./EdgeNodeProviderService
    ports:
      - 4500:4500

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    environment: 
      - MINIO_ACCESS_KEY=dev_access_key
      - MINIO_SECRET_KEY=dev_secret_key
    command: minio server /data

  edge1:
    build: ./EdgeNode
    expose: 
      - "22"
    ports:
      - "2222:22"
      - "8080:80"

  elasticsearch1:
    image: elasticsearch:7.8.0
    ports:
      - 9200:9200
      - 9300:9300
    expose: 
      - 9200
      - 9300
    environment: 
      - "discovery.type=single-node"

